const chats=[
{id:1,name:"Maya Chen",initials:"MC",preview:"Thanks! The plan looks good. ✅",time:"9:41 AM",unread:2,color:"#c06f5a",online:true},
{id:2,name:"Dev Team",initials:"</>",preview:"Alex: The API fix is deployed.",time:"9:28 AM",unread:3,color:"#7f66c9",online:true},
{id:3,name:"Jordan Patel",initials:"JP",preview:"Sounds good, let’s sync later.",time:"Yesterday",color:"#a7805a"},
{id:4,name:"Product Updates",initials:"↗",preview:"Priya: New feedback collected",time:"Yesterday",unread:6,color:"#d39416"},
{id:5,name:"Samir Qureshi",initials:"SQ",preview:"Can you share the report?",time:"Tue",unread:1,color:"#3a8f85",online:true},
{id:6,name:"Support Escalations",initials:"!",preview:"Escalated to tier 2",time:"Mon",color:"#d84c4c"},
{id:7,name:"Design Team",initials:"✎",preview:"Shared a design",time:"Mon",color:"#3e78bd"}];
let activeId=1,members=[{id:1,name:"Maya Chen",online:true},{id:2,name:"Alex Morgan",online:true},{id:3,name:"Priya Shah",online:false}];
const messages={1:[{text:"Hi Chris! Do you have the latest quarterly plan we discussed?",time:"9:35 AM"},{mine:true,text:"Hi Maya! Yes, here it is.",time:"9:36 AM"},{mine:true,file:"Q2_2026_Quarterly_Plan.pdf",time:"9:36 AM"},{text:"Thanks! I’ll review and get back to you.",time:"9:37 AM"},{text:"Looks comprehensive. I’ve added a few comments.",time:"9:40 AM"},{mine:true,text:"Thanks! The plan looks good. ✅",time:"9:41 AM"}]};
let audit=[["Admin started oversight","Today, 9:00 AM"],["Admin viewed messages","Today, 9:05 AM"],["Exported conversation","Today, 9:22 AM"]];
const perms=[["View messages","Admins can view messages in real time"],["Manage users","Imran can add or remove any user"],["Export history","Admins can export conversation history"],["Restrict attachments","Admins can block file uploads"]],$=s=>document.querySelector(s),now=()=>new Date().toLocaleTimeString([],{hour:"numeric",minute:"2-digit"});
function current(){return chats.find(c=>c.id===activeId)||chats[0]}
function renderChats(q=""){ $("#chatList").innerHTML=chats.filter(c=>(c.name+c.preview).toLowerCase().includes(q.toLowerCase())).map(c=>`<button class="chat-row ${c.id===activeId?"selected":""}" data-chat="${c.id}"><span class="avatar" style="background:${c.color}">${c.initials}<i class="${c.online?"online":""}"></i></span><span class="chat-copy"><b>${c.name}</b><small>${c.preview}</small></span><span class="chat-meta"><time>${c.time}</time>${c.unread?`<em>${c.unread}</em>`:""}</span></button>`).join("");document.querySelectorAll("[data-chat]").forEach(b=>b.onclick=()=>{activeId=+b.dataset.chat;render();show("conversation")})}
function renderMessages(){const c=current(),list=messages[activeId]||[{text:`Start a conversation with ${c.name}.`,time:"Now"}];$("#messages").innerHTML=list.map(m=>`<div class="message ${m.mine?"mine":""} ${m.file?"file-message":""}">${m.file?`<span class="pdf">PDF</span><span class="file-copy"><b>${m.file}</b><small>PDF · 1.8 MB</small></span><button>⇩</button>`:`<span>${m.text}</span>`}<time>${m.time}${m.mine?" ✓✓":""}</time></div>`).join("")}
function render(){const c=current();$("#activeName").textContent=c.name;$("#activeStatus").textContent=c.online?"● Online":"Last seen recently";$("#activeAvatar").innerHTML=`${c.initials}<i class="${c.online?"online":""}"></i>`;$("#activeAvatar").style.background=c.color;$("#messageInput").placeholder=`Message ${c.name}`;renderChats($("#search").value);renderMessages()}
function renderAudit(){$("#auditList").innerHTML=audit.slice(0,6).map(a=>`<div class="audit-row"><span>◉</span><p><b>${a[0]}</b><small>${a[1]}</small></p><em>Admin</em></div>`).join("")}
function renderMembers(){$("#memberList").innerHTML=members.map(m=>`<div class="member-row"><span class="member-dot" data-online="${m.online}"></span><p><b>${m.name}</b><small>User · ${m.online?"Online":"Offline"}</small></p><button data-remove="${m.id}">Remove</button></div>`).join("");document.querySelectorAll("[data-remove]").forEach(b=>b.onclick=()=>{const m=members.find(x=>x.id===+b.dataset.remove);if(confirm(`Remove ${m.name}?`)){members=members.filter(x=>x.id!==m.id);const i=chats.findIndex(c=>c.name===m.name);if(i>-1)chats.splice(i,1);audit.unshift([`Removed ${m.name}`,now()]);renderMembers();renderAudit();render()}})}
function show(p){document.querySelectorAll(".sidebar,.conversation,.admin-panel").forEach(x=>x.classList.remove("mobile-active"));document.querySelector(p==="chats"?".sidebar":p==="admin"?".admin-panel":".conversation").classList.add("mobile-active")}
$("#search").oninput=e=>renderChats(e.target.value);$("#composer").onsubmit=e=>{e.preventDefault();let t=$("#messageInput").value.trim();if(!t)return;(messages[activeId]??=[]).push({mine:true,text:t,time:now()});$("#messageInput").value="";renderMessages()};
$("#deleteChat").onclick=()=>{let c=current();if(confirm(`Delete your chat with ${c.name}?`)){chats.splice(chats.findIndex(x=>x.id===activeId),1);delete messages[activeId];activeId=chats[0]?.id;render()}};
$("#permissions").innerHTML=perms.map((p,i)=>`<div class="permission"><span><b>${p[0]}</b><small>${p[1]}</small></span><button class="switch ${i<3?"on":""}"><i></i></button></div>`).join("");document.querySelectorAll(".switch").forEach((b,i)=>b.onclick=()=>{b.classList.toggle("on");audit.unshift([`${perms[i][0]} ${b.classList.contains("on")?"enabled":"disabled"}`,now()]);renderAudit()});
$("#manageUsers").onclick=()=>{let p=$("#memberManager");p.hidden=!p.hidden;$("#manageUsers").textContent=p.hidden?"Manage users":"Close user manager"};$("#addMember").onsubmit=e=>{e.preventDefault();let name=$("#newMember").value.trim();if(!name)return;let id=Date.now();members.push({id,name,online:false});chats.push({id,name,initials:name.split(" ").map(x=>x[0]).join("").slice(0,2).toUpperCase(),preview:"Start a private conversation",time:"New",color:"#3a8f85"});audit.unshift([`Added ${name}`,now()]);$("#newMember").value="";renderMembers();renderAudit();render()};
document.querySelectorAll("[data-panel]").forEach(b=>b.onclick=()=>show(b.dataset.panel));render();renderAudit();renderMembers();show(innerWidth<=700?"chats":"conversation");
