import { createClient } from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm";
import { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY } from "./config.js";

const supabase=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);
const $=s=>document.querySelector(s);
let session=null,profile=null,contacts=[],activeContact=null,activeConversation=null,pendingFile=null,messageChannel=null;
const escapeHtml=value=>String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const initials=name=>name.split(/\s+/).map(x=>x[0]).join("").slice(0,2).toUpperCase();
const accountEmail=name=>`${[...new TextEncoder().encode(name.trim().toLowerCase())].map(x=>x.toString(16).padStart(2,"0")).join("")}@relaydesk.local`;
function toast(text,error=false){const el=$("#toast");el.textContent=text;el.className=`toast show ${error?"error":""}`;clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.className="toast",3500)}
function busy(form,on){form.querySelectorAll("button,input").forEach(x=>x.disabled=on)}
function showAuth(mode="signup"){$("#authView").hidden=false;$("#appView").hidden=true;$("#signupPanel").hidden=mode!=="signup";$("#loginPanel").hidden=mode!=="login"}
$("#showLogin").onclick=()=>showAuth("login");$("#showSignup").onclick=()=>showAuth("signup");

$("#signupForm").onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,name=$("#signupName").value.trim(),password=$("#signupPassword").value;busy(form,true);const{error}=await supabase.auth.signUp({email:accountEmail(name),password,options:{data:{display_name:name}}});busy(form,false);if(error)return toast(error.message,true);await supabase.auth.signOut();$("#loginName").value=name;showAuth("login");toast("Account created. Log in to continue.")};
$("#loginForm").onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,name=$("#loginName").value.trim(),password=$("#loginPassword").value;busy(form,true);const{error}=await supabase.auth.signInWithPassword({email:accountEmail(name),password});busy(form,false);if(error)return toast("Name or password is incorrect.",true);await boot()};
$("#logoutBtn").onclick=async()=>{await supabase.auth.signOut();cleanup();showAuth("login")};
function cleanup(){session=profile=activeContact=activeConversation=null;if(messageChannel)supabase.removeChannel(messageChannel)}

async function boot(){const{data:{session:s}}=await supabase.auth.getSession();if(!s)return showAuth("signup");session=s;const{data:p,error}=await supabase.from("profiles").select("id,display_name,is_admin,is_active").eq("id",s.user.id).single();if(error||!p)return toast("Your profile could not be loaded.",true);if(!p.is_active){await supabase.auth.signOut();return toast("This account has been disabled.",true)}profile=p;$("#authView").hidden=true;$("#appView").hidden=false;$("#appView").classList.toggle("has-admin",p.is_admin);$("#adminPanel").hidden=!p.is_admin;$("#profileName").textContent=p.display_name;$("#profileAvatar").textContent=initials(p.display_name);$("#accountRole").textContent=p.is_admin?"Administrator":"Private messaging";document.querySelectorAll(".admin-only").forEach(x=>x.hidden=!p.is_admin);await loadContacts();if(p.is_admin)await loadAdmin()};
async function loadContacts(){const{data,error}=await supabase.from("profiles").select("id,display_name,is_active").neq("id",profile.id).eq("is_active",true).order("display_name");if(error)return toast(error.message,true);contacts=data??[];renderContacts()}
function renderContacts(){const q=$("#userSearch").value.toLowerCase();$("#contactList").innerHTML=contacts.filter(x=>x.display_name.toLowerCase().includes(q)).map(x=>`<button class="contact ${activeContact?.id===x.id?"active":""}" data-user="${x.id}"><span class="avatar">${escapeHtml(initials(x.display_name))}</span><span><b>${escapeHtml(x.display_name)}</b><small>Open private chat</small></span><small>›</small></button>`).join("")||`<div class="empty-state"><p>No other users yet.</p></div>`;document.querySelectorAll("[data-user]").forEach(b=>b.onclick=()=>openContact(b.dataset.user))}
$("#userSearch").oninput=renderContacts;
async function openContact(id){activeContact=contacts.find(x=>x.id===id);renderContacts();$("#activeName").textContent=activeContact.display_name;$("#activeStatus").textContent="Private conversation";$("#activeAvatar").textContent=initials(activeContact.display_name);const{data,error}=await supabase.rpc("start_private_chat",{other_user:id});if(error)return toast(error.message,true);activeConversation=data;$("#emptyChat").hidden=true;$("#messageStage").hidden=false;$("#composer").hidden=false;$("#deleteChatBtn").disabled=false;await loadMessages();subscribeMessages();showPanel("chat")}
async function loadMessages(){const{data,error}=await supabase.from("messages").select("id,body,created_at,sender_id,attachment_path,attachment_name,attachment_type,sender:profiles!messages_sender_id_fkey(display_name)").eq("conversation_id",activeConversation).order("created_at");if(error)return toast(error.message,true);await renderMessages(data??[])}
async function attachmentUrl(path){if(!path)return null;const{data}=await supabase.storage.from("chat-files").createSignedUrl(path,3600);return data?.signedUrl??null}
async function renderMessages(rows){const rendered=await Promise.all(rows.map(async m=>{const mine=m.sender_id===profile.id,url=await attachmentUrl(m.attachment_path),image=m.attachment_type?.startsWith("image/");return `<article class="message ${mine?"mine":""}">${m.body?`<div>${escapeHtml(m.body)}</div>`:""}${url?`<div class="attachment">${image?`<img src="${url}" alt="${escapeHtml(m.attachment_name)}">`:""}<a href="${url}" target="_blank" rel="noopener">⇩ ${escapeHtml(m.attachment_name)}</a></div>`:""}<time>${new Date(m.created_at).toLocaleTimeString([],{hour:"numeric",minute:"2-digit"})}</time></article>`}));$("#messages").innerHTML=rendered.join("");$("#messageStage").scrollTop=$("#messageStage").scrollHeight}
function subscribeMessages(){if(messageChannel)supabase.removeChannel(messageChannel);messageChannel=supabase.channel(`chat-${activeConversation}`).on("postgres_changes",{event:"INSERT",schema:"public",table:"messages",filter:`conversation_id=eq.${activeConversation}`},()=>loadMessages()).subscribe()}
$("#fileInput").onchange=e=>{pendingFile=e.target.files[0]??null;if(pendingFile&&pendingFile.size>10*1024*1024){pendingFile=null;e.target.value="";return toast("Files must be 10 MB or smaller.",true)}$("#filePreview").hidden=!pendingFile;$("#filePreview").textContent=pendingFile?`Ready to send: ${pendingFile.name}`:""};
$("#composer").onsubmit=async e=>{e.preventDefault();const body=$("#messageInput").value.trim();if(!body&&!pendingFile)return;let path=null,name=null,type=null;const sendBtn=e.currentTarget.querySelector(".send");sendBtn.disabled=true;if(pendingFile){name=pendingFile.name;type=pendingFile.type||"application/octet-stream";path=`${profile.id}/${crypto.randomUUID()}-${name.replace(/[^a-zA-Z0-9._-]/g,"_")}`;const{error}=await supabase.storage.from("chat-files").upload(path,pendingFile,{contentType:type});if(error){sendBtn.disabled=false;return toast(error.message,true)}}const{error}=await supabase.from("messages").insert({conversation_id:activeConversation,sender_id:profile.id,body:body||null,attachment_path:path,attachment_name:name,attachment_type:type});sendBtn.disabled=false;if(error)return toast(error.message,true);$("#messageInput").value="";$("#fileInput").value="";pendingFile=null;$("#filePreview").hidden=true;await loadMessages()};
$("#deleteChatBtn").onclick=async()=>{if(!activeConversation||!confirm("Delete this chat from your account?"))return;const{error}=await supabase.rpc("leave_conversation",{target_conversation:activeConversation});if(error)return toast(error.message,true);activeConversation=activeContact=null;$("#emptyChat").hidden=false;$("#messageStage").hidden=true;$("#composer").hidden=true;$("#deleteChatBtn").disabled=true;$("#activeName").textContent="Select a person";$("#activeAvatar").textContent="";renderContacts();toast("Chat removed from your account.")};

async function loadAdmin(){const{data:messages}=await supabase.from("messages").select("id,body,created_at,attachment_path,attachment_name,attachment_type,sender:profiles!messages_sender_id_fkey(display_name)").order("created_at",{ascending:false}).limit(100);const rows=await Promise.all((messages??[]).map(async m=>({...m,url:await attachmentUrl(m.attachment_path)})));$("#adminMessages").innerHTML=rows.map(m=>`<div class="admin-item"><p><b>${escapeHtml(m.sender?.display_name||"User")}</b><small>${escapeHtml(m.body||m.attachment_name||"Attachment")}</small>${m.url?`<a href="${m.url}" target="_blank">Open file</a>`:""}</p><em>${new Date(m.created_at).toLocaleString()}</em></div>`).join("")||"<p class='muted'>No chat activity yet.</p>";const{data:users}=await supabase.from("profiles").select("id,display_name,is_active,is_admin").order("display_name");$("#adminUsers").innerHTML=(users??[]).map(u=>`<div class="user-row"><p><b>${escapeHtml(u.display_name)}${u.is_admin?" · Admin":""}</b><small>${u.is_active?"Active":"Disabled"}</small></p>${u.id!==profile.id?`<button data-toggle-user="${u.id}" data-active="${u.is_active}">${u.is_active?"Disable":"Enable"}</button>`:""}</div>`).join("");document.querySelectorAll("[data-toggle-user]").forEach(b=>b.onclick=()=>toggleUser(b.dataset.toggleUser,b.dataset.active==="true"))}
async function toggleUser(id,active){const{error}=await supabase.from("profiles").update({is_active:!active}).eq("id",id);if(error)return toast(error.message,true);await loadAdmin()}
document.querySelectorAll("[data-admin-tab]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-admin-tab]").forEach(x=>x.classList.toggle("active",x===b));$("#adminMessages").hidden=b.dataset.adminTab!=="messages";$("#adminUsers").hidden=b.dataset.adminTab!=="users"});
function showPanel(name){if(innerWidth>1100)return;document.querySelectorAll(".sidebar,.conversation,.admin-panel").forEach(x=>x.classList.remove("mobile-active"));document.querySelector(name==="contacts"?".sidebar":name==="admin"?".admin-panel":".conversation").classList.add("mobile-active")}
document.querySelectorAll("[data-panel]").forEach(b=>b.onclick=()=>showPanel(b.dataset.panel));$("#openAdminBtn").onclick=()=>showPanel("admin");
supabase.auth.onAuthStateChange((event)=>{if(event==="SIGNED_OUT")showAuth("login")});boot();
