-- RelayDesk database, authorization, realtime, and private file storage.
-- Run once in Supabase Dashboard > SQL Editor.

create schema if not exists private;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null,
  is_admin boolean not null default false,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);
create unique index if not exists profiles_display_name_lower_idx on public.profiles (lower(display_name));

create table if not exists public.conversations (
  id uuid primary key default gen_random_uuid(),
  created_by uuid not null references public.profiles(id),
  created_at timestamptz not null default now()
);

create table if not exists public.conversation_members (
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  joined_at timestamptz not null default now(),
  primary key (conversation_id,user_id)
);
create index if not exists conversation_members_user_idx on public.conversation_members(user_id);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  sender_id uuid not null references public.profiles(id),
  body text,
  attachment_path text,
  attachment_name text,
  attachment_type text,
  created_at timestamptz not null default now(),
  constraint message_has_content check (nullif(trim(body),'') is not null or attachment_path is not null)
);
create index if not exists messages_conversation_created_idx on public.messages(conversation_id,created_at);

create or replace function private.is_admin()
returns boolean language sql stable security definer set search_path=public
as $$ select coalesce((select is_admin and is_active from public.profiles where id=(select auth.uid())),false) $$;

create or replace function private.is_member(target uuid)
returns boolean language sql stable security definer set search_path=public
as $$ select exists(select 1 from public.conversation_members where conversation_id=target and user_id=(select auth.uid())) $$;

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path=public
as $$
begin
  insert into public.profiles(id,display_name)
  values(new.id,trim(coalesce(new.raw_user_meta_data->>'display_name','User')));
  return new;
end $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

create or replace function public.start_private_chat(other_user uuid)
returns uuid language plpgsql security definer set search_path=public
as $$
declare chat_id uuid;
begin
  if other_user=(select auth.uid()) or not exists(select 1 from profiles where id=other_user and is_active) then raise exception 'Invalid user'; end if;
  select c.id into chat_id from conversations c
  where exists(select 1 from conversation_members m where m.conversation_id=c.id and m.user_id=(select auth.uid()))
    and exists(select 1 from conversation_members m where m.conversation_id=c.id and m.user_id=other_user)
    and (select count(*) from conversation_members m where m.conversation_id=c.id)=2
  limit 1;
  if chat_id is null then
    insert into conversations(created_by) values((select auth.uid())) returning id into chat_id;
    insert into conversation_members(conversation_id,user_id) values(chat_id,(select auth.uid())),(chat_id,other_user);
  end if;
  return chat_id;
end $$;

create or replace function public.leave_conversation(target_conversation uuid)
returns void language plpgsql security definer set search_path=public
as $$ begin delete from conversation_members where conversation_id=target_conversation and user_id=(select auth.uid()); end $$;

revoke all on function public.start_private_chat(uuid) from public;
revoke all on function public.leave_conversation(uuid) from public;
grant execute on function public.start_private_chat(uuid),public.leave_conversation(uuid) to authenticated;

alter table public.profiles enable row level security;
alter table public.conversations enable row level security;
alter table public.conversation_members enable row level security;
alter table public.messages enable row level security;

drop policy if exists "authenticated profiles" on public.profiles;
create policy "authenticated profiles" on public.profiles for select to authenticated using ((select auth.uid()) is not null);
drop policy if exists "admin updates profiles" on public.profiles;
create policy "admin updates profiles" on public.profiles for update to authenticated using ((select private.is_admin())) with check ((select private.is_admin()));

drop policy if exists "members view conversations" on public.conversations;
create policy "members view conversations" on public.conversations for select to authenticated using ((select private.is_admin()) or (select private.is_member(id)));
drop policy if exists "members view membership" on public.conversation_members;
create policy "members view membership" on public.conversation_members for select to authenticated using ((select private.is_admin()) or (select private.is_member(conversation_id)));
drop policy if exists "members view messages" on public.messages;
create policy "members view messages" on public.messages for select to authenticated using ((select private.is_admin()) or (select private.is_member(conversation_id)));
drop policy if exists "members send messages" on public.messages;
create policy "members send messages" on public.messages for insert to authenticated with check (sender_id=(select auth.uid()) and (select private.is_member(conversation_id)));

grant select on public.profiles,public.conversations,public.conversation_members,public.messages to authenticated;
grant insert on public.messages to authenticated;
grant update(is_active) on public.profiles to authenticated;
grant usage,select on sequence public.messages_id_seq to authenticated;

insert into storage.buckets(id,name,public,file_size_limit)
values('chat-files','chat-files',false,10485760)
on conflict(id) do update set public=false,file_size_limit=10485760;

drop policy if exists "users upload own chat files" on storage.objects;
create policy "users upload own chat files" on storage.objects for insert to authenticated
with check(bucket_id='chat-files' and (storage.foldername(name))[1]=(select auth.uid())::text);
drop policy if exists "members view chat files" on storage.objects;
create policy "members view chat files" on storage.objects for select to authenticated
using(bucket_id='chat-files' and ((select private.is_admin()) or exists(
  select 1 from public.messages m where m.attachment_path=name and (select private.is_member(m.conversation_id))
)));
drop policy if exists "owners delete chat files" on storage.objects;
create policy "owners delete chat files" on storage.objects for delete to authenticated
using(bucket_id='chat-files' and ((storage.foldername(name))[1]=(select auth.uid())::text or (select private.is_admin())));

do $$ begin
  alter publication supabase_realtime add table public.messages;
exception when duplicate_object then null;
end $$;

-- After Imran signs up, run this once with his exact account name:
-- update public.profiles set is_admin=true where lower(display_name)=lower('Imran Sohail');
